# CSE-221710308039-VINAY

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv('https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/cities.csv')
data

,name_of_city,state_code,state_name,dist_code,population_total,population_male,population_female,0-6_population_total,0-6_population_male,0-6_population_female,...,literates_female,sex_ratio,child_sex_ratio,effective_literacy_rate_total,effective_literacy_rate_male,effective_literacy_rate_female,location,total_graduates,male_graduates,female_graduates
0,Abohar,3,PUNJAB,9,145238,76840,68398,15870,8587,7283,...,44972,890,848,79.86,85.49,73.59,"30.1452928,74.1993043",16287,8612,7675
1,Achalpur,27,MAHARASHTRA,7,112293,58256,54037,11810,6186,5624,...,43086,928,909,91.99,94.77,89.00,"21.257584,77.5086754",8863,5269,3594
2,Adilabad,28,ANDHRA PRADESH,1,117388,59232,58156,13103,6731,6372,...,37660,982,947,80.51,88.18,72.73,"19.0809075,79.560344",10565,6797,3768
3,Adityapur,20,JHARKHAND,24,173988,91495,82493,23042,12063,10979,...,54515,902,910,83.46,89.98,76.23,"22.7834741,86.1576889",19225,12189,7036
4,Adoni,28,ANDHRA PRADESH,21,166537,82743,83794,18406,9355,9051,...,45089,1013,968,68.38,76.58,60.33,"15.6322227,77.2728368",11902,7871,4031
5,Agartala,16,TRIPURA,1,399688,199616,200072,33635,17341,16294,...,169109,1002,940,93.88,95.75,92.02,"23.831457,91.2867777",52711,30215,22496
6,Agra,9,UTTAR PRADESH,15,1574542,849771,724771,186516,105279,81237,...,376725,853,772,63.44,67.67,58.54,"27.1766701,78.0080745",185813,106082,79731
7,Ahmadabad,24,GUJARAT,7,5570585,2935869,2634716,589076,317917,271159,...,2004480,897,853,89.62,93.96,84.81,"23.022505,72.5713621",769858,435267,334591
8,Ahmadnagar,27,MAHARASHTRA,26,350905,179755,171150,36712,19748,16964,...,134649,952,859,91.49,95.51,87.33,"19.0952075,74.7495916",51661,29832,21829
9,Aizawl,15,MIZORAM,3,291822,143803,148019,35147,17667,17480,...,128332,1029,989,98.80,99.30,98.31,"23.727107,92.7176389",26832,14900,11932
10,Ajmer,8,RAJASTHAN,21,542580,278786,263794,59437,31547,27890,...,192327,946,884,87.53,93.26,81.53,"26.4498954,74.6399163",77989,42454,35535
11,Akbarpur,9,UTTAR PRADESH,47,111594,57560,54034,14037,7247,6790,...,32854,939,937,76.94,83.89,69.54,"26.4407468,82.5537514",9745,5811,3934
12,Akola,27,MAHARASHTRA,5,427146,218184,208962,46500,24488,22012,...,164093,958,899,91.34,94.78,87.77,"20.7059345,77.0219019",49715,28812,20903
13,Alandur,33,TAMIL NADU,3,164162,82190,81972,14486,7336,7150,...,69660,997,975,95.15,97.20,93.10,"12.9974873,80.2006371",45971,25463,20508
14,Alappuzha,32,KERALA,11,174164,83888,90276,15434,7934,7500,...,78815,1076,945,96.56,98.03,95.21,"9.4980667,76.3388484",22263,9900,12363
15,Aligarh,9,UTTAR PRADESH,12,872575,463123,409452,113658,60620,53038,...,230083,884,875,70.36,75.50,64.55,"27.8973944,78.0880129",99341,55965,43376
16,Allahabad,9,UTTAR PRADESH,44,1117094,601363,515731,102556,54660,47896,...,384409,858,876,86.50,90.21,82.17,"25.4358011,81.846311",233129,138248,94881
17,Alwar,8,RAJASTHAN,6,315310,166900,148410,34576,18862,15714,...,104897,889,833,86.78,93.72,79.05,"27.5529907,76.6345735",58764,35297,23467
18,Ambala,6,HARYANA,2,196216,103533,92683,19645,10713,8932,...,70776,895,834,88.23,91.58,84.51,"30.3781788,76.7766974",34943,17809,17134
19,Ambala Sadar,6,HARYANA,2,104268,54241,50027,9646,5239,4407,...,39792,922,841,87.97,88.66,87.22,"30.3248708,76.8432663",20618,10689,9929
20,Ambarnath,27,MAHARASHTRA,21,254003,133006,120997,27465,14406,13059,...,90434,910,906,89.04,93.82,83.78,"19.1825167,73.1926023",26596,14444,12152
21,Ambattur,33,TAMIL NADU,1,478134,241181,236953,45216,23065,22151,...,192505,982,960,92.69,95.71,89.62,"13.1143167,80.1480551",97186,52224,44962
22,Ambikapur,22,CHHATTISGARH,2,114575,59673,54902,12995,6887,6108,...,40640,920,887,88.20,92.73,83.29,"23.1354921,83.1817856",20857,12369,8488
23,Ambur,33,TAMIL NADU,4,113856,56052,57804,12150,6216,5934,...,42870,1031,955,86.83,91.18,82.65,"12.7903613,78.7166084",7813,5076,2737
24,Amravati,27,MAHARASHTRA,7,646801,330544,316257,62497,32713,29784,...,259078,957,910,93.03,95.52,90.44,"20.9374238,77.7795513",91996,51456,40540
25,Amreli,24,GUJARAT,13,105980,55166,50814,9885,5386,4499,...,39254,921,835,89.47,93.85,84.75,"21.6031774,71.2220832",11305,6579,4726
26,Amritsar,3,PUNJAB,15,1132761,602754,530007,109540,60056,49484,...,394465,879,824,85.27,88.09,82.09,"31.6339793,74.8722642",140359,69241,71118
27,Amroha,9,UTTAR PRADESH,6,197135,102804,94331,26855,13799,13056,...,48151,918,946,63.88,68.11,59.24,"28.9043537,78.4673426",13879,7635,6244
28,Anand,24,GUJARAT,15,197351,102359,94992,19993,10631,9362,...,77767,928,881,93.71,96.42,90.82,"22.5645175,72.928871",29803,17331,12472
29,Anantapur,28,ANDHRA PRADESH,22,262340,131506,130834,23630,12409,11221,...,90000,995,904,81.88,88.54,75.24,"14.6818877,77.6005911",43700,27392,16308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,Tirunelveli,33,TAMIL NADU,27,474838,234643,240195,43988,22511,21477,...,190463,1024,954,90.98,94.99,87.08,"8.7139126,77.7566523",59397,33536,25861
464,Tirupati,28,ANDHRA PRADESH,23,287035,145977,141058,24643,12869,11774,...,106281,966,915,87.55,92.74,82.21,"13.6287557,79.4191795",55454,34588,20866
465,Tiruppur,33,TAMIL NADU,32,444543,227469,217074,45091,23039,22052,...,160710,954,957,87.67,92.69,82.41,"11.1085242,77.3410656",33358,18431,14927
466,Tiruvannamalai,33,TAMIL NADU,5,144683,72351,72332,14530,7413,7117,...,50671,1000,960,81.64,85.60,77.70,"12.2252841,79.0746957",16502,9655,6847
467,Tiruvottiyur,33,TAMIL NADU,1,248059,124852,123207,24007,12185,11822,...,94449,987,970,88.21,91.59,84.80,"13.1691914,80.3045793",25781,13493,12288
468,Titagarh,19,WEST BENGAL,11,118426,63936,54490,10816,5729,5087,...,36790,852,888,81.18,86.87,74.47,"22.7382665,88.3737064",5643,3898,1745
469,Tonk,8,RAJASTHAN,22,165363,84927,80436,23122,12280,10842,...,41649,947,883,69.47,78.70,59.85,"26.1620402,75.7894716",11776,7537,4239
470,Tumkur,29,KARNATAKA,17,305821,155406,150415,29655,15233,14422,...,113520,968,947,85.97,88.39,83.47,"13.3709627,76.6412712",42163,25617,16546
471,Udaipur,8,RAJASTHAN,32,451735,234681,217054,47352,25338,22014,...,166547,925,869,90.66,95.56,85.39,"24.585445,73.712479",92090,51475,40615
472,Udgir,27,MAHARASHTRA,28,104063,54445,49618,13075,6933,6142,...,34533,911,886,85.78,91.59,79.43,"18.3942882,77.1126009",9924,6900,3024
473,Udupi,29,KARNATAKA,15,125350,62031,63319,10283,5364,4919,...,53351,1021,917,93.89,96.51,91.35,"13.3408807,74.7421427",22444,11795,10649
474,Ujjain,23,MADHYA PRADESH,18,515215,265291,249924,57630,30007,27623,...,176989,942,921,85.55,91.16,79.62,"23.1793013,75.7849097",72743,41616,31127
475,Ulhasnagar,27,MAHARASHTRA,21,506937,270373,236564,48513,25492,23021,...,180984,875,903,89.21,93.10,84.75,"19.2215115,73.1644628",43561,23087,20474
476,Uluberia,19,WEST BENGAL,15,222175,114144,108031,25187,12991,12196,...,73616,946,939,81.13,85.23,76.82,"22.4744363,88.1000377",11384,7234,4150
477,Unnao,9,UTTAR PRADESH,25,178681,94080,84601,18604,9949,8655,...,60607,899,870,83.72,87.26,79.80,"26.5393449,80.4878195",27220,15670,11550
478,Uttarpara Kotrung,19,WEST BENGAL,12,162386,82815,79571,11140,5815,5325,...,65893,961,916,91.16,93.48,88.75,"22.6768451,88.3385053",35773,20981,14792
479,Vadodara,24,GUJARAT,19,1666703,866701,800002,156480,84307,72173,...,647672,923,856,92.37,95.51,88.99,"22.3071588,73.1812187",279959,153236,126723
480,Valsad,24,GUJARAT,24,114987,58958,56029,9609,5119,4490,...,46240,950,877,92.70,95.56,89.72,"20.5992349,72.9342451",18980,10382,8598
481,Varanasi,9,UTTAR PRADESH,66,1201815,636860,564955,129180,68761,60419,...,381572,887,879,80.12,84.11,75.63,"25.3176452,82.9739144",172622,101440,71182
482,Vasai Virar City,27,MAHARASHTRA,21,1221233,649535,571698,137343,71716,65627,...,439778,880,915,91.15,94.86,86.90,"19.3919275,72.8397317",129954,70016,59938
483,Vellore,33,TAMIL NADU,4,185895,91464,94431,18363,9305,9058,...,69871,1032,973,86.67,91.68,81.84,"12.9165167,79.1324986",15592,8912,6680
484,Veraval,24,GUJARAT,12,153696,78161,75535,17107,9003,8104,...,46666,966,900,78.00,86.58,69.21,"20.9158979,70.3628516",10089,6246,3843
485,Vidisha,23,MADHYA PRADESH,26,155959,81424,74535,19360,10122,9238,...,52876,915,913,86.88,92.29,80.98,"23.5251102,77.8081363",22023,13177,8846
486,Vijayawada,28,ANDHRA PRADESH,16,1048240,524918,523322,92848,47582,45266,...,377361,997,951,82.59,86.24,78.94,"16.5061743,80.6480153",135425,81146,54279
487,Visakhapatnam,28,ANDHRA PRADESH,13,1730320,875199,855121,158924,81119,77805,...,599937,977,959,82.66,88.02,77.18,"17.6868,83.2185",250549,148824,101725
488,Vizianagaram,28,ANDHRA PRADESH,12,227533,111596,115937,20487,10495,9992,...,80306,1039,952,81.85,88.18,75.80,"18.1066576,83.3955506",30656,19173,11483
489,Warangal,28,ANDHRA PRADESH,9,620116,310400,309716,55392,28434,26958,...,217136,998,948,84.16,91.54,76.79,"17.9689008,79.5940544",109613,69507,40106
490,Wardha,27,MAHARASHTRA,8,105543,53241,52302,9754,5139,4615,...,43339,982,898,94.05,97.19,90.88,"20.745319,78.6021946",19363,10645,8718
491,Yamunanagar,6,HARYANA,3,216628,115404,101224,22905,12556,10349,...,74255,877,824,85.91,89.61,81.71,"30.1290485,77.2673901",29803,14349,15454
492,Yavatmal,27,MAHARASHTRA,14,116714,58717,57997,11081,5894,5187,...,46561,988,880,91.81,95.45,88.17,"20.3887937,78.1204073",13511,7397,6114

In [3]:
#Analyze the  top 5 cities with highest number of female graduates
fhigh=data.sort_values(by='female_graduates',ascending=False).head()
fhigh

,name_of_city,state_code,state_name,dist_code,population_total,population_male,population_female,0-6_population_total,0-6_population_male,0-6_population_female,...,literates_female,sex_ratio,child_sex_ratio,effective_literacy_rate_total,effective_literacy_rate_male,effective_literacy_rate_female,location,total_graduates,male_graduates,female_graduates
141,Delhi,7,NCT OF DELHI,99,11007835,5871362,5136473,1209275,647938,561337,...,3806615,875,866,87.60,91.44,83.20,"28.7041,77.1025",2221137,1210040,1011097
185,Greater Mumbai,27,MAHARASHTRA,99,12478447,6736815,5741632,1139146,599007,540139,...,4509812,852,902,90.28,93.32,86.70,"19.0760,72.8777",1802371,964964,837407
72,Bengaluru,29,KARNATAKA,18,8425970,4401299,4024671,862493,444639,417854,...,3110983,914,940,89.59,92.63,86.25,"12.9716,77.5946",1591163,908363,682800
184,Greater Hyderabad,28,ANDHRA PRADESH,99,6809970,3500802,3309168,725816,373794,352022,...,2359594,945,942,82.96,85.96,79.79,"17.3850,78.4867",1164149,685402,478747
119,Chennai,33,TAMIL NADU,2,4681087,2357633,2323454,418541,213084,205457,...,1845974,986,964,90.33,93.47,87.16,"13.0826802,80.2707184",879695,487428,392267

In [4]:
#Find the 5 cities with lowest number of female graduates and concatenate the two dataframes of top 5 cities with  bottom 5 cities
flow=data.sort_values(by='female_graduates').head()
flow

,name_of_city,state_code,state_name,dist_code,population_total,population_male,population_female,0-6_population_total,0-6_population_male,0-6_population_female,...,literates_female,sex_ratio,child_sex_ratio,effective_literacy_rate_total,effective_literacy_rate_male,effective_literacy_rate_female,location,total_graduates,male_graduates,female_graduates
131,Dabgram,19,WEST BENGAL,2,118464,60708,57756,14472,7427,7045,...,34149,951,949,73.98,80.29,67.34,"26.6954603,88.4415998",2532,1703,829
39,Bagaha,10,BIHAR,1,113012,59946,53066,19070,9802,9268,...,22247,885,946,60.67,69.30,50.79,"27.1221959,84.0722375",3744,2756,988
234,Jamuria,19,WEST BENGAL,9,144971,75574,69397,17556,9017,8539,...,38753,918,947,73.11,81.73,63.68,"23.7060688,87.0774107",5436,3961,1475
374,Pithampur,23,MADHYA PRADESH,21,126099,70577,55522,20438,10872,9566,...,33387,787,880,82.73,90.49,72.65,"22.613252,75.6822899",5150,3657,1493
323,Mustafabad,7,NCT OF DELHI,3,127012,66754,60258,19370,10176,9194,...,34201,903,903,76.10,84.33,66.98,"28.7113968,77.2681086",4462,2950,1512

In [5]:
data1=pd.concat([fhigh,flow])
data1

,name_of_city,state_code,state_name,dist_code,population_total,population_male,population_female,0-6_population_total,0-6_population_male,0-6_population_female,...,literates_female,sex_ratio,child_sex_ratio,effective_literacy_rate_total,effective_literacy_rate_male,effective_literacy_rate_female,location,total_graduates,male_graduates,female_graduates
141,Delhi,7,NCT OF DELHI,99,11007835,5871362,5136473,1209275,647938,561337,...,3806615,875,866,87.60,91.44,83.20,"28.7041,77.1025",2221137,1210040,1011097
185,Greater Mumbai,27,MAHARASHTRA,99,12478447,6736815,5741632,1139146,599007,540139,...,4509812,852,902,90.28,93.32,86.70,"19.0760,72.8777",1802371,964964,837407
72,Bengaluru,29,KARNATAKA,18,8425970,4401299,4024671,862493,444639,417854,...,3110983,914,940,89.59,92.63,86.25,"12.9716,77.5946",1591163,908363,682800
184,Greater Hyderabad,28,ANDHRA PRADESH,99,6809970,3500802,3309168,725816,373794,352022,...,2359594,945,942,82.96,85.96,79.79,"17.3850,78.4867",1164149,685402,478747
119,Chennai,33,TAMIL NADU,2,4681087,2357633,2323454,418541,213084,205457,...,1845974,986,964,90.33,93.47,87.16,"13.0826802,80.2707184",879695,487428,392267
131,Dabgram,19,WEST BENGAL,2,118464,60708,57756,14472,7427,7045,...,34149,951,949,73.98,80.29,67.34,"26.6954603,88.4415998",2532,1703,829
39,Bagaha,10,BIHAR,1,113012,59946,53066,19070,9802,9268,...,22247,885,946,60.67,69.30,50.79,"27.1221959,84.0722375",3744,2756,988
234,Jamuria,19,WEST BENGAL,9,144971,75574,69397,17556,9017,8539,...,38753,918,947,73.11,81.73,63.68,"23.7060688,87.0774107",5436,3961,1475
374,Pithampur,23,MADHYA PRADESH,21,126099,70577,55522,20438,10872,9566,...,33387,787,880,82.73,90.49,72.65,"22.613252,75.6822899",5150,3657,1493
323,Mustafabad,7,NCT OF DELHI,3,127012,66754,60258,19370,10176,9194,...,34201,903,903,76.10,84.33,66.98,"28.7113968,77.2681086",4462,2950,1512

In [6]:
#Display only the rows which belong to Kerala, Bihar and Maharashtra.
data[data['state_name'].isin(["MAHARASHTRA","BIHAR","KERALA"])].sort_values(by='female_graduates')

,name_of_city,state_code,state_name,dist_code,population_total,population_male,population_female,0-6_population_total,0-6_population_male,0-6_population_female,...,literates_female,sex_ratio,child_sex_ratio,effective_literacy_rate_total,effective_literacy_rate_male,effective_literacy_rate_female,location,total_graduates,male_graduates,female_graduates
39,Bagaha,10,BIHAR,1,113012,59946,53066,19070,9802,9268,...,22247,885,946,60.67,69.30,50.79,"27.1221959,84.0722375",3744,2756,988
236,Jehanabad,10,BIHAR,37,102456,54868,47588,14516,7706,6810,...,30163,867,884,79.66,84.58,73.97,"25.1515827,84.981754",8901,6620,2281
269,Kishanganj,10,BIHAR,8,107076,55688,51388,17017,8743,8274,...,29804,923,946,74.71,79.84,69.13,"26.0917422,87.9383822",7847,5536,2311
472,Udgir,27,MAHARASHTRA,28,104063,54445,49618,13075,6933,6142,...,34533,911,886,85.78,91.59,79.43,"18.3942882,77.1126009",9924,6900,3024
230,Jamalpur,10,BIHAR,24,105221,56231,48990,12298,6587,5711,...,35231,871,867,87.38,92.58,81.40,"25.312717,86.4906091",10638,7165,3473
111,Buxar,10,BIHAR,30,102591,54123,48468,13639,7260,6379,...,33151,896,879,85.16,90.91,78.76,"25.4987785,84.1435136",12464,8920,3544
1,Achalpur,27,MAHARASHTRA,7,112293,58256,54037,11810,6186,5624,...,43086,928,909,91.99,94.77,89.00,"21.257584,77.5086754",8863,5269,3594
34,Aurangabad,10,BIHAR,33,101520,53307,48213,14292,7548,6744,...,33458,904,893,86.89,92.52,80.68,"24.7457189,84.3804888",13141,9371,3770
338,Nandurbar,27,MAHARASHTRA,1,111067,57543,53524,12621,6868,5753,...,38962,930,838,86.99,92.10,81.56,"21.7468548,74.123996",11451,7441,4010
73,Bettiah,10,BIHAR,1,132896,70381,62515,18203,9685,8518,...,42116,888,880,82.54,86.57,78.00,"26.8028048,84.5169757",13438,9372,4066
140,Dehri,10,BIHAR,32,137068,72311,64757,18372,9570,8802,...,42552,896,920,83.38,89.92,76.05,"24.9277351,84.1909841",14780,10297,4483
211,Hinganghat,27,MAHARASHTRA,8,100416,51881,48535,9681,5175,4506,...,39871,936,871,94.34,97.91,90.56,"20.5505728,78.8411405",11256,6684,4572
63,Barshi,27,MAHARASHTRA,30,118573,60857,57716,13029,7060,5969,...,41295,948,845,86.47,92.88,79.80,"18.2333856,75.6941478",13351,8564,4787
440,Siwan,10,BIHAR,16,134458,70670,63788,17632,9440,8192,...,42746,903,868,84.65,91.71,76.89,"26.2196205,84.3566593",14545,9727,4818
356,Osmanabad,27,MAHARASHTRA,29,112085,58098,53987,13346,7184,6162,...,39464,929,858,88.15,93.45,82.52,"18.2069636,76.1783739",14303,9459,4844
196,Hajipur,10,BIHAR,18,147126,78561,68565,20090,10694,9396,...,43154,873,879,79.26,84.78,72.93,"25.6858392,85.2145907",16319,11371,4948
413,Saharsa,10,BIHAR,12,155175,82589,72586,24582,12814,11768,...,42736,879,918,77.66,84.11,70.27,"25.8834961,86.6006249",18307,13209,5098
419,Sasaram,10,BIHAR,32,147396,77687,69709,19363,10189,9174,...,46478,897,900,82.31,87.26,76.78,"24.949036,84.0314295",18844,13181,5663
318,Motihari,10,BIHAR,2,125183,67438,57745,16325,8891,7434,...,42022,856,836,87.20,90.36,83.52,"26.6469624,84.9088938",19550,13634,5916
153,Dinapur Nizamat,10,BIHAR,28,182241,97129,85112,25092,13398,11694,...,52413,876,873,78.40,84.54,71.39,"25.6328264,85.0597137",19777,13707,6070
492,Yavatmal,27,MAHARASHTRA,14,116714,58717,57997,11081,5894,5187,...,46561,988,880,91.81,95.45,88.17,"20.3887937,78.1204073",13511,7397,6114
321,Munger,10,BIHAR,24,213101,113173,99928,29260,15323,13937,...,65864,883,910,81.83,86.43,76.59,"25.3747561,86.4735251",19988,13825,6163
95,Bid,27,MAHARASHTRA,27,146237,75655,70582,19580,10626,8954,...,51036,933,843,88.56,94.01,82.81,"18.9890893,75.7600785",19030,12252,6778
117,Chapra,10,BIHAR,17,201597,106250,95347,27668,14516,13152,...,62447,897,906,81.30,86.07,75.97,"25.7795649,84.7498886",22852,15710,7142
259,Katihar,10,BIHAR,10,225982,119142,106840,31036,16054,14982,...,68125,897,933,79.87,84.96,74.16,"25.552048,87.5718609",24259,17105,7154
98,Biharsharif,10,BIHAR,27,296889,154915,141974,43646,22758,20888,...,79173,916,918,74.80,83.42,65.39,"25.1982147,85.5148735",28092,20487,7605
69,Begusarai,10,BIHAR,20,251136,133931,117205,37966,20012,17954,...,72702,875,897,79.35,84.67,73.25,"25.416675,86.1293792",24616,16492,8124
182,Gondiya,27,MAHARASHTRA,11,132889,66756,66133,12835,6652,6183,...,53769,991,929,93.70,97.70,89.69,"21.4624491,80.2209773",18563,10175,8388
358,Palakkad,32,KERALA,6,131019,63833,67186,11614,5930,5684,...,56414,1053,959,94.20,96.83,91.73,"10.7867303,76.6547932",16827,8436,8391
382,Purnia,10,BIHAR,9,280547,148021,132526,41046,21081,19965,...,77646,895,947,74.48,79.36,68.98,"25.7771391,87.4752551",28193,19787,8406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,Bhagalpur,10,BIHAR,22,398138,212005,186133,53775,28061,25714,...,122420,878,916,81.16,85.38,76.31,"25.3478004,86.9824288",49656,33692,15964
116,Chandrapur,27,MAHARASHTRA,13,321036,165125,155911,30353,15921,14432,...,121434,944,906,90.81,95.53,85.83,"19.9704597,79.3014845",37686,21317,16369
175,Gaya,10,BIHAR,34,463454,245764,217690,59015,30966,28049,...,152370,886,906,85.74,90.49,80.35,"24.7954523,84.999431",56679,38831,17848
366,Panvel,27,MAHARASHTRA,24,180464,93135,87329,17512,9213,8299,...,72348,938,901,93.98,96.27,91.54,"18.9894007,73.1175162",39613,20964,18649
337,Nanded Waghala,27,MAHARASHTRA,15,550564,286152,264412,68181,36417,31764,...,190157,924,872,87.40,92.68,81.74,"19.1428869,77.303723",57736,38146,19590
475,Ulhasnagar,27,MAHARASHTRA,21,506937,270373,236564,48513,25492,23021,...,180984,875,903,89.21,93.10,84.75,"19.2215115,73.1644628",43561,23087,20474
12,Akola,27,MAHARASHTRA,5,427146,218184,208962,46500,24488,22012,...,164093,958,899,91.34,94.78,87.77,"20.7059345,77.0219019",49715,28812,20903
325,Muzaffarpur,10,BIHAR,14,351838,186145,165693,42276,22287,19989,...,118090,890,897,85.16,88.83,81.05,"26.1208876,85.3647201",61914,40575,21339
275,Kollam,32,KERALA,13,349033,168076,180957,31304,16018,15286,...,149927,1077,954,92.10,93.85,90.50,"8.8932118,76.6141396",39521,17708,21813
8,Ahmadnagar,27,MAHARASHTRA,26,350905,179755,171150,36712,19748,16964,...,134649,952,859,91.49,95.51,87.33,"19.0952075,74.7495916",51661,29832,21829
227,Jalgaon,27,MAHARASHTRA,3,460468,241228,219240,51544,28548,22996,...,165352,909,806,88.96,93.30,84.26,"21.0076578,75.5626039",55315,33154,22161
417,Sangli Miraj Kupwad,27,MAHARASHTRA,35,502697,255270,247427,51536,27524,24012,...,184692,969,872,88.08,93.39,82.67,"16.8541887,74.6049061",60752,34112,26640
461,Thrissur,32,KERALA,7,315596,151999,163597,25252,12953,12299,...,145644,1076,950,97.24,98.31,96.26,"10.5276416,76.2144349",53535,24392,29143
278,Kozhikode,32,KERALA,4,432097,206494,225603,41574,21208,20366,...,196582,1093,960,96.80,97.93,95.78,"11.2587531,75.78041",61225,27701,33524
441,Solapur,27,MAHARASHTRA,30,951118,482194,468924,104466,54728,49738,...,319845,972,909,83.88,91.31,76.30,"17.6599188,75.9063906",88638,54159,34479
273,Kolhapur,27,MAHARASHTRA,34,549283,280820,268463,49914,27245,22669,...,215743,956,832,92.12,96.32,87.77,"16.7049873,74.2432527",92443,52599,39844
24,Amravati,27,MAHARASHTRA,7,646801,330544,316257,62497,32713,29784,...,259078,957,910,93.03,95.52,90.44,"20.9374238,77.7795513",91996,51456,40540
310,Mira Bhayander,27,MAHARASHTRA,21,814655,434330,380325,84238,44688,39550,...,308494,876,885,93.67,96.41,90.53,"19.2952325,72.8543897",118506,65979,52527
482,Vasai Virar City,27,MAHARASHTRA,21,1221233,649535,571698,137343,71716,65627,...,439778,880,915,91.15,94.86,86.90,"19.3919275,72.8397317",129954,70016,59938
271,Kochi,32,KERALA,8,601574,296668,304906,52466,26863,25603,...,270062,1028,953,97.49,98.31,96.69,"9.9312328,76.2673041",115773,54538,61235
35,Aurangabad,27,MAHARASHTRA,19,1171330,610377,560953,151827,81671,70156,...,411321,919,859,89.13,94.08,83.81,"19.8761653,75.3433139",159308,96576,62732
459,Thiruvananthapuram,32,KERALA,14,752490,364657,387833,61619,31156,30463,...,330865,1064,978,93.72,94.94,92.58,"8.5241391,76.9366376",151257,72759,78498
343,Navi Mumbai,27,MAHARASHTRA,21,1119477,611501,507976,124015,65230,58785,...,392285,831,901,91.57,95.05,87.33,"19.0330488,73.0296625",192624,107448,85176
342,Nashik,27,MAHARASHTRA,20,1486973,784995,701978,169753,91457,78296,...,539559,894,856,90.96,94.96,86.51,"19.9974533,73.7898023",204014,116855,87159
373,Pimpri Chinchwad,27,MAHARASHTRA,25,1729359,945953,783406,216695,116421,100274,...,590002,828,861,90.90,94.63,86.37,"18.6297811,73.7997094",249581,141573,108008
371,Patna,10,BIHAR,28,1683200,894158,789042,190496,102208,88288,...,569943,882,864,84.71,87.71,81.33,"25.5940947,85.1375645",307603,199207,108396
456,Thane,27,MAHARASHTRA,21,1818872,966293,852579,186259,98017,88242,...,673724,882,900,91.36,94.19,88.14,"19.2183307,72.9780897",241148,129214,111934
334,Nagpur,27,MAHARASHTRA,9,2405421,1226610,1178811,237865,123851,114014,...,958239,961,921,93.13,96.16,89.99,"21.1458004,79.0881546",382282,201349,180933
380,Pune,27,MAHARASHTRA,25,3115431,1602137,1513294,324572,171152,153420,...,1195486,945,896,91.61,95.13,87.91,"18.5204303,73.8567437",656508,349022,307486
185,Greater Mumbai,27,MAHARASHTRA,99,12478447,6736815,5741632,1139146,599007,540139,...,4509812,852,902,90.28,93.32,86.70,"19.0760,72.8777",1802371,964964,837407

In [7]:
#Find the top 10 cities with highest total graduation rate
gdata=data.sort_values(by='total_graduates',ascending=False).head(10)
gdata

,name_of_city,state_code,state_name,dist_code,population_total,population_male,population_female,0-6_population_total,0-6_population_male,0-6_population_female,...,literates_female,sex_ratio,child_sex_ratio,effective_literacy_rate_total,effective_literacy_rate_male,effective_literacy_rate_female,location,total_graduates,male_graduates,female_graduates
141,Delhi,7,NCT OF DELHI,99,11007835,5871362,5136473,1209275,647938,561337,...,3806615,875,866,87.60,91.44,83.20,"28.7041,77.1025",2221137,1210040,1011097
185,Greater Mumbai,27,MAHARASHTRA,99,12478447,6736815,5741632,1139146,599007,540139,...,4509812,852,902,90.28,93.32,86.70,"19.0760,72.8777",1802371,964964,837407
72,Bengaluru,29,KARNATAKA,18,8425970,4401299,4024671,862493,444639,417854,...,3110983,914,940,89.59,92.63,86.25,"12.9716,77.5946",1591163,908363,682800
184,Greater Hyderabad,28,ANDHRA PRADESH,99,6809970,3500802,3309168,725816,373794,352022,...,2359594,945,942,82.96,85.96,79.79,"17.3850,78.4867",1164149,685402,478747
119,Chennai,33,TAMIL NADU,2,4681087,2357633,2323454,418541,213084,205457,...,1845974,986,964,90.33,93.47,87.16,"13.0826802,80.2707184",879695,487428,392267
274,Kolkata,19,WEST BENGAL,16,4486679,2362662,2124017,300052,155475,144577,...,1682088,899,930,87.14,89.08,84.98,"22.572646,88.363895",818476,461615,356861
7,Ahmadabad,24,GUJARAT,7,5570585,2935869,2634716,589076,317917,271159,...,2004480,897,853,89.62,93.96,84.81,"23.022505,72.5713621",769858,435267,334591
380,Pune,27,MAHARASHTRA,25,3115431,1602137,1513294,324572,171152,153420,...,1195486,945,896,91.61,95.13,87.91,"18.5204303,73.8567437",656508,349022,307486
288,Lucknow,9,UTTAR PRADESH,26,2815601,1470133,1345468,280817,147690,133127,...,986314,915,901,84.72,87.81,81.36,"26.8466937,80.946166",596990,326431,270559
225,Jaipur,8,RAJASTHAN,12,3073350,1619280,1454070,378788,204320,174468,...,990584,898,854,84.34,90.61,77.41,"26.9124336,75.7872709",533148,319107,214041

In [8]:
#Calculate the average child sex ratio of the Kerala State.
data[data['state_name'].isin(["KERALA"])].child_sex_ratio.mean()

957.0

# 2.Mean = 70 and Standard Deviation = 10 ,Identify how much area can be found between 70 and 90 with help of Empirical Rule.

### The empirical rule is a statistical rule which states that for a normal distribution, almost all data will fall within three standard deviations of the mean. Broken down, the empirical rule shows that 68% will fall within the first standard deviation, 95% within the first two standard deviations,99.7% within the first three standard deviations.

- As we know the area between 50 and 90 is 95% (i.e between first 2 standard deviations),the area between 70 and 90 will be 47.5% which is half the area of 95%.

### Therefore required area is 47.5%